# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpt < Formula
  desc "Manipulates the route files for the Greater Patagonia Trail."
  homepage ""
  version "0.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/dave/gpt/releases/download/v0.2.0/gpt_0.2.0_Darwin_x86_64.tar.gz"
    sha256 "f563c8023bcfdd0a9ee10c87b5ea426b6cc24f934b0017fe324279b59ab73427"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/dave/gpt/releases/download/v0.2.0/gpt_0.2.0_Darwin_arm64.tar.gz"
    sha256 "4388737032b52ad9a800719556d8cafd5682e67c769c60d6cff3e30dc0d8053e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dave/gpt/releases/download/v0.2.0/gpt_0.2.0_Linux_x86_64.tar.gz"
    sha256 "7d3879969c5bea72a97dad7f2635647d70ba637b5dd7e10976a0df7525ff92c6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dave/gpt/releases/download/v0.2.0/gpt_0.2.0_Linux_arm64.tar.gz"
    sha256 "6faec064998db5514b8a7be532ed5be95364d72a9b09b54b57c54c810606a009"
  end

  def install
    bin.install "gpt"
  end
end
